{% set version = "0.1.0" %}

package:
  name: raven
  version: {{ version }}

source:
  url: https://github.com/CSHS-CWRA/raven-feedstock/raw/main/raven/src/Raven-rev288.zip
  #path: ../Raven-rev288

build:
  build: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - make  # [not win]
  host:
    - libnetcdf
  run:
    - libnetcdf

about:
  home: http://raven.uwaterloo.ca/
  dev_url: https://chyms.nrc.gc.ca/
  docs_url: http://raven.uwaterloo.ca/files/v3.0.4/RavenManual_v3.0.4.pdf
  doc_source_url: http://raven.uwaterloo.ca/Downloads.html
  license: Artistic-2.0
  license_file: LICENSE
  summary: This is an experimental conda binary for the Raven hydrological model.

extra:
  maintainers:
    - Zeitsperre
    - cjauvin
