{% set name = "Raven" %}
{% set version = "3.0.4" %}
{% set revision = "318" %}

package:
  name: {{ name|lower }}
  version: {{ version }}.{{ revision }}

source:
  url: http://www.civil.uwaterloo.ca/jmai/{{ name|lower }}/{{ name }}-rev{{ revision }}.zip
  # git_url:
  # git_rev:

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - make  # [not win]
  host:
    - libnetcdf
  run:
    - libnetcdf

about:
  home: http://raven.uwaterloo.ca/
  dev_url: https://chyms.nrc.gc.ca/
  docs_url: http://raven.uwaterloo.ca/files/v{{ version }}/RavenManual_v{{ version }}.pdf
  doc_source_url: http://raven.uwaterloo.ca/Downloads.html
  license: Artistic-2.0
  license_file: LICENSE
  summary: This is an experimental conda binary for the Raven hydrological model.

extra:
  maintainers:
    - Zeitsperre
    - cjauvin
