{% set name = "Raven" %}
{% set version = "3.0.4" %}
{% set revision = "322" %}

package:
  name: {{ name|lower }}
  version: {{ version }}.{{ revision }}

source:
  url: http://www.civil.uwaterloo.ca/jmai/{{ name|lower }}/{{ name }}-rev{{ revision }}.zip
  sha256: 96513a51db42c81875347fc4d56cb323ec7feab71a9c4b7f8b03d2144552e582

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - libnetcdf  {{ libnetcdf }}
  host:
    - libnetcdf  {{ libnetcdf }}
  run:
    - libnetcdf  {{ libnetcdf }}

test:
  commands:
    - test -f $PREFIX/bin/raven
    - raven -v

about:
  home: http://raven.uwaterloo.ca/
  dev_url: https://chyms.nrc.gc.ca/
  doc_url: http://raven.uwaterloo.ca/files/v{{ version }}/RavenManual_v{{ version }}.pdf
  doc_source_url: http://raven.uwaterloo.ca/Downloads.html
  license: Artistic-2.0
  license_file: LICENSE
  summary: This is an experimental conda binary for the Raven hydrological model.

extra:
  maintainers:
    - Zeitsperre
    - cjauvin
