{% set version = "0.1.1" %}

package:
  name: raven
  version: {{ version }}

source:
  url: http://www.civil.uwaterloo.ca/jmai/raven/Raven-rev312.zip
  # git_url:
  # git_rev:

build:
  noarch: generic
#  run_exports:
#    strong:
#      - libnetcdf

requirements:
  build:
    - {{ compiler('cxx') }}
    - make  # [not win]
  host:
    - libnetcdf
  run:
    - libnetcdf

about:
  home: http://raven.uwaterloo.ca/
  dev_url: https://chyms.nrc.gc.ca/
  docs_url: http://raven.uwaterloo.ca/files/v3.0.4/RavenManual_v3.0.4.pdf
  doc_source_url: http://raven.uwaterloo.ca/Downloads.html
  license: Artistic-2.0
  license_file: LICENSE
  summary: This is an experimental conda binary for the Raven hydrological model.

extra:
  maintainers:
    - Zeitsperre
    - cjauvin
