{% set name = "ravenpy" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a4eb054bded6a990783c3ea1d52263779c7083b0fa5e0e9df0ba8174c9101890
  # If not set to tagged commit, will pull from master. caveat emptor.
  # git_url: https://github.com/CSHS-CWRA/RavenPy.git
  # git_rev: v0.4.0

build:
  # noarch: python
  skip: true  # [win]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - setuptools
    - gdal >=3
    - pip
  run:
    # I don't know if :: syntax does anything here. Can only be specified in conda-build command.
    - zeitsperre::raven
    - zeitsperre::ostrich
    - python
    - affine
    - click
    - climpred >=2.1
    - clisops >=0.6.3
    - dask <=2021.02.0
    - gdal >=3
    - geopandas >=0.9
    - libnetcdf
    - lxml
    - matplotlib
    - numpy >=1.20
    - owslib
    - pandas >=1.2
    - pyproj >=3
    - rasterio
    - requests
    - rioxarray
    - scipy
    - shapely
    - statsmodels
    - xarray >=0.17
    - xclim >=0.23
    - xskillscore <=0.0.19

test:
  imports:
    - ravenpy

about:
  home: https://github.com/CSHS-CWRA/RavenPy
  dev_url: https://github.com/CSHS-CWRA/RavenPy
  doc_url: https://ravenpy.readthedocs.io/en/latest/
  license: MIT
  license_file: LICENSE
  summary: This is an experimental conda binary for the RavenPy python library.

extra:
  maintainers:
    - Zeitsperre
