package:
  name: ravenpy
  version: 0.3.0
source:
  path: .
requirements:
  build:
    - python
    - setuptools
  run:
    - raven   # binary dep, only in cjauvin channel
#    - ostrich # binary dep, only in cjauvin channel
    - python
    - click
    - matplotlib
    - netCDF4
    - numpy >=1.20
    - pandas >=1.2
    - requests
    - scipy
    - statsmodels
    - xarray >=0.17
    - xclim >=0.23
    - xskillscore
    - climpred >=2.1